export const rows = [
  {
    id: 1,
    date: "2023-10-27",
    escrowID: "ESC123456",
    buyerUsername: "johndoe123",
    merchantUsername: "shopkeeper321",
    amount: 100.5,
    productType: "Electronics",
    deliveryStatus: "Delivered",
    buyerFullname: "John Doe",
    buyerAddress: "123 Main Street, Anytown, USA",
    buyerPhone: "555-555-5555",
    buyerEmail: "john.doe@example.com",
    buyerAccNo: "987654321",
    buyerPickUpStation: "Central Station",
    merchantFullname: "Jane Smith",
    merchantAddress: "456 Oak Avenue, Somewhere, USA",
    merchantPhone: "555-555-5555",
    merchantEmail: "jane.smith@example.com",
    merchantAccNo: "123456789",
    merchantDropOffLocation: "West Depot",
    transactionStatus: "pending",
    trackingNumber: "ABC123456789",
  },
  {
    id: 2,
    date: "2023-10-28",
    escrowID: "ESC234567",
    buyerUsername: "janedoe456",
    merchantUsername: "shopkeeper321",
    amount: 75.25,
    productType: "Clothing",
    deliveryStatus: "On transit",
    buyerFullname: "Jane Doe",
    buyerAddress: "456 Elm Street, Someplace, USA",
    buyerPhone: "555-555-5555",
    buyerEmail: "jane.doe@example.com",
    buyerAccNo: "123456789",
    buyerPickUpStation: "East Station",
    merchantFullname: "Bob Johnson",
    merchantAddress: "789 Maple Drive, Elsewhere, USA",
    merchantPhone: "555-555-5555",
    merchantEmail: "bob.johnson@example.com",
    merchantAccNo: "987654321",
    merchantDropOffLocation: "North Depot",
    transactionStatus: "in progress",
    trackingNumber: "DEF234567890",
  },
  {
    id: 3,
    date: "2023-10-29",
    escrowID: "ESC345678",
    buyerUsername: "marysmith789",
    merchantUsername: "shophere123",
    amount: 120.75,
    productType: "Home Decor",
    deliveryStatus: "Not Shipped",
    buyerFullname: "Mary Smith",
    buyerAddress: "789 Pine Lane, Nowhere, USA",
    buyerPhone: "555-555-5555",
    buyerEmail: "mary.smith@example.com",
    buyerAccNo: "234567890",
    buyerPickUpStation: "South Station",
    merchantFullname: "Chris Brown",
    merchantAddress: "012 Cedar Court, Anywhere, USA",
    merchantPhone: "555-555-5555",
    merchantEmail: "chris.brown@example.com",
    merchantAccNo: "345678901",
    merchantDropOffLocation: "Central Depot",
    transactionStatus: "disputed",
    trackingNumber: "GHI345678901",
  },
  {
    id: 4,
    date: "2023-10-30",
    escrowID: "ESC456789",
    buyerUsername: "alexandergreen",
    merchantUsername: "bestdeals22",
    amount: 200.0,
    productType: "Books",
    deliveryStatus: "Delivered",
    buyerFullname: "Alexander Green",
    buyerAddress: "234 Oak Street, Everywhere, USA",
    buyerPhone: "555-555-5555",
    buyerEmail: "alex.green@example.com",
    buyerAccNo: "345678901",
    buyerPickUpStation: "West Station",
    merchantFullname: "Emily Davis",
    merchantAddress: "345 Birch Avenue, Anytown, USA",
    merchantPhone: "555-555-5555",
    merchantEmail: "emily.davis@example.com",
    merchantAccNo: "456789012",
    merchantDropOffLocation: "East Depot",
    transactionStatus: "pending",
    trackingNumber: "JKL456789012",
  },
  {
    id: 5,
    date: "2023-11-01",
    escrowID: "ESC567890",
    buyerUsername: "sarahjones",
    merchantUsername: "sellmore55",
    amount: 150.75,
    productType: "Electronics",
    deliveryStatus: "On transit",
    buyerFullname: "Sarah Jones",
    buyerAddress: "567 Cedar Lane, Somewhere, USA",
    buyerPhone: "555-555-5555",
    buyerEmail: "sarah.jones@example.com",
    buyerAccNo: "456789012",
    buyerPickUpStation: "North Station",
    merchantFullname: "Michael Johnson",
    merchantAddress: "678 Pine Drive, Anywhere, USA",
    merchantPhone: "555-555-5555",
    merchantEmail: "michael.johnson@example.com",
    merchantAccNo: "567890123",
    merchantDropOffLocation: "South Depot",
    transactionStatus: "in progress",
    trackingNumber: "MNO567890123",
  },
  {
    id: 6,
    date: "2023-11-02",
    escrowID: "ESC678901",
    buyerUsername: "davidmiller",
    merchantUsername: "bestdeals22",
    amount: 85.5,
    productType: "Clothing",
    deliveryStatus: "Delivered",
    buyerFullname: "David Miller",
    buyerAddress: "890 Maple Court, Anywhere, USA",
    buyerPhone: "555-555-5555",
    buyerEmail: "david.miller@example.com",
    buyerAccNo: "567890123",
    buyerPickUpStation: "East Station",
    merchantFullname: "Emily Davis",
    merchantAddress: "345 Birch Avenue, Anytown, USA",
    merchantPhone: "555-555-5555",
    merchantEmail: "emily.davis@example.com",
    merchantAccNo: "456789012",
    merchantDropOffLocation: "West Depot",
    transactionStatus: "disputed",
    trackingNumber: "PQR678901234",
  },
  {
    id: 7,
    date: "2023-11-03",
    escrowID: "ESC789012",
    buyerUsername: "laurawilson",
    merchantUsername: "shophere123",
    amount: 60.25,
    productType: "Home Decor",
    deliveryStatus: "Not Shipped",
    buyerFullname: "Laura Wilson",
    buyerAddress: "901 Pine Drive, Elsewhere, USA",
    buyerPhone: "555-555-5555",
    buyerEmail: "laura.wilson@example.com",
    buyerAccNo: "678901234",
    buyerPickUpStation: "South Station",
    merchantFullname: "Chris Brown",
    merchantAddress: "012 Cedar Court, Anywhere, USA",
    merchantPhone: "555-555-5555",
    merchantEmail: "chris.brown@example.com",
    merchantAccNo: "345678901",
    merchantDropOffLocation: "North Depot",
    transactionStatus: "pending",
    trackingNumber: "STU789012345",
  },
  {
    id: 8,
    date: "2023-11-04",
    escrowID: "ESC890123",
    buyerUsername: "jenniferadams",
    merchantUsername: "sellmore55",
    amount: 95.75,
    productType: "Books",
    deliveryStatus: "On transit",
    buyerFullname: "Jennifer Adams",
    buyerAddress: "012 Oak Avenue, Nowhere, USA",
    buyerPhone: "555-555-5555",
    buyerEmail: "jennifer.adams@example.com",
    buyerAccNo: "789012345",
    buyerPickUpStation: "Central Station",
    merchantFullname: "Michael Johnson",
    merchantAddress: "678 Pine Drive, Anywhere, USA",
    merchantPhone: "555-555-5555",
    merchantEmail: "michael.johnson@example.com",
    merchantAccNo: "567890123",
    merchantDropOffLocation: "East Depot",
    transactionStatus: "in progress",
    trackingNumber: "VWX890123456",
  },
  {
    id: 9,
    date: "2023-11-05",
    escrowID: "ESC901234",
    buyerUsername: "williamtaylor",
    merchantUsername: "bestdeals22",
    amount: 130.0,
    productType: "Electronics",
    deliveryStatus: "Delivered",
    buyerFullname: "William Taylor",
    buyerAddress: "123 Cedar Court, Everywhere, USA",
    buyerPhone: "555-555-5555",
    buyerEmail: "william.taylor@example.com",
    buyerAccNo: "890123456",
    buyerPickUpStation: "North Station",
    merchantFullname: "Emily Davis",
    merchantAddress: "345 Birch Avenue, Anytown, USA",
    merchantPhone: "555-555-5555",
    merchantEmail: "emily.davis@example.com",
    merchantAccNo: "456789012",
    merchantDropOffLocation: "West Depot",
    transactionStatus: "disputed",
    trackingNumber: "YZA901234567",
  },
  {
    id: 10,
    date: "2023-11-06",
    escrowID: "ESC012345",
    buyerUsername: "susanbrown",
    merchantUsername: "shophere123",
    amount: 70.5,
    productType: "Clothing",
    deliveryStatus: "Not Shipped",
    buyerFullname: "Susan Brown",
    buyerAddress: "234 Pine Lane, Someplace, USA",
    buyerPhone: "555-555-5555",
    buyerEmail: "susan.brown@example.com",
    buyerAccNo: "901234567",
    buyerPickUpStation: "West Station",
    merchantFullname: "Chris Brown",
    merchantAddress: "012 Cedar Court, Anywhere, USA",
    merchantPhone: "555-555-5555",
    merchantEmail: "chris.brown@example.com",
    merchantAccNo: "345678901",
    merchantDropOffLocation: "Central Depot",
    transactionStatus: "pending",
    trackingNumber: "BCD012345678",
  },
];